INSERT INTO burgers (name) VALUES ('Green-Chile Burgers with Fried Eggs');
INSERT INTO burgers (name) VALUES ('Umami Burgers with Port and Stilton');
INSERT INTO burgers (name) VALUES ('Bacon and Avocado on Brioche Buns', true);
INSERT INTO burgers (name) VALUES ('Cheddar and Onion, Stuffed and Smashed', true);
INSERT INTO burgers (name) VALUES ('Cheddar BLT with Tarragon Dressing', true);
INSERT INTO burgers (name) VALUES ('Torta with Cheese and Chile-Stuffed patty');
INSERT INTO burgers (name) VALUES ('All American, Onion Lettuce and Tomato');
INSERT INTO burgers (name) VALUES ('50/50 Burger, Half Bacon Meat Patty');
INSERT INTO burgers (name) VALUES ('Hawaii Burger, with Pineapple and Teriyaki');
INSERT INTO burgers (name) VALUES ('Peanut-Chipotle Barbecue A5 Waygu Beef');
